// Mock for @expo/vector-icons
module.exports = {
  __esModule: true,
  Ionicons: 'Ionicons',
  MaterialIcons: 'MaterialIcons',
  MaterialCommunityIcons: 'MaterialCommunityIcons',
  FontAwesome: 'FontAwesome',
  FontAwesome5: 'FontAwesome5',
  AntDesign: 'AntDesign',
  Entypo: 'Entypo',
  EvilIcons: 'EvilIcons',
  Feather: 'Feather',
  Foundation: 'Foundation',
  Octicons: 'Octicons',
  SimpleLineIcons: 'SimpleLineIcons',
  Zocial: 'Zocial',
  // Mock components
  Ionicons: jest.fn(() => null),
  MaterialIcons: jest.fn(() => null),
  MaterialCommunityIcons: jest.fn(() => null),
  FontAwesome: jest.fn(() => null),
  FontAwesome5: jest.fn(() => null),
  AntDesign: jest.fn(() => null),
  Entypo: jest.fn(() => null),
  EvilIcons: jest.fn(() => null),
  Feather: jest.fn(() => null),
  Foundation: jest.fn(() => null),
  Octicons: jest.fn(() => null),
  SimpleLineIcons: jest.fn(() => null),
  Zocial: jest.fn(() => null),
};
